/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as nativeCurrencyPaymentFallbackSol from './NativeCurrencyPaymentFallback.sol/index.js';
export * as storageAccessibleSol from './StorageAccessible.sol/index.js';