/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as createCallSol from './CreateCall.sol/index.js';
export type { createCallSol };
import type * as multiSendSol from './MultiSend.sol/index.js';
export type { multiSendSol };
import type * as multiSendCallOnlySol from './MultiSendCallOnly.sol/index.js';
export type { multiSendCallOnlySol };
import type * as safeMigrationSol from './SafeMigration.sol/index.js';
export type { safeMigrationSol };
import type * as safeToL2SetupSol from './SafeToL2Setup.sol/index.js';
export type { safeToL2SetupSol };
import type * as signMessageLibSol from './SignMessageLib.sol/index.js';
export type { signMessageLibSol };