// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface INativeCurrencyPaymentFallback$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "INativeCurrencyPaymentFallback";
  readonly sourceName: "contracts/interfaces/INativeCurrencyPaymentFallback.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"sender","type":"address"},{"indexed":false,"internalType":"uint256","name":"value","type":"uint256"}],"name":"SafeReceived","type":"event"},{"stateMutability":"payable","type":"receive"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/INativeCurrencyPaymentFallback.sol";
  readonly buildInfoId: "solc-0_8_28-ed2d128c3ac1e98a551cdd21051ecbf6dd081352";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["INativeCurrencyPaymentFallback"]: INativeCurrencyPaymentFallback$Type;
    ["contracts/interfaces/INativeCurrencyPaymentFallback.sol:INativeCurrencyPaymentFallback"]: INativeCurrencyPaymentFallback$Type;
  }
}