/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IERC165Handler, IERC165HandlerInterface } from "../../../../handler/extensible/ERC165Handler.sol/IERC165Handler.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes4",
        "name": "interfaceId",
        "type": "bytes4"
      },
      {
        "internalType": "bytes32[]",
        "name": "handlerWithSelectors",
        "type": "bytes32[]"
      }
    ],
    "name": "addSupportedInterfaceBatch",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes4",
        "name": "interfaceId",
        "type": "bytes4"
      },
      {
        "internalType": "bytes4[]",
        "name": "selectors",
        "type": "bytes4[]"
      }
    ],
    "name": "removeSupportedInterfaceBatch",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "contract ISafe",
        "name": "safe",
        "type": "address"
      },
      {
        "internalType": "bytes4",
        "name": "interfaceId",
        "type": "bytes4"
      }
    ],
    "name": "safeInterfaces",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes4",
        "name": "interfaceId",
        "type": "bytes4"
      },
      {
        "internalType": "bool",
        "name": "supported",
        "type": "bool"
      }
    ],
    "name": "setSupportedInterface",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IERC165Handler__factory {
    static readonly abi = _abi;
    static createInterface(): IERC165HandlerInterface {
      return new Interface(_abi) as IERC165HandlerInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IERC165Handler {
      return new Contract(address, _abi, runner) as unknown as IERC165Handler;
    }
  }
  