/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC165Handler__factory } from './ERC165Handler__factory.js';
export { IERC165Handler__factory } from './IERC165Handler__factory.js';