/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as safeProxySol from './SafeProxy.sol/index.js';
export type { safeProxySol };
import type * as safeProxyFactorySol from './SafeProxyFactory.sol/index.js';
export type { safeProxyFactorySol };