/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../common.js"
  import type { CreateCall, CreateCallInterface } from "../../../libraries/CreateCall.sol/CreateCall.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "newContract",
        "type": "address"
      }
    ],
    "name": "ContractCreation",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "value",
        "type": "uint256"
      },
      {
        "internalType": "bytes",
        "name": "deploymentData",
        "type": "bytes"
      }
    ],
    "name": "performCreate",
    "outputs": [
      {
        "internalType": "address",
        "name": "newContract",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "value",
        "type": "uint256"
      },
      {
        "internalType": "bytes",
        "name": "deploymentData",
        "type": "bytes"
      },
      {
        "internalType": "bytes32",
        "name": "salt",
        "type": "bytes32"
      }
    ],
    "name": "performCreate2",
    "outputs": [
      {
        "internalType": "address",
        "name": "newContract",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b506103128061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610034575f3560e01c80634847be6f146100385780634c8c9ea114610067575b5f5ffd5b61004b61004636600461024c565b61007a565b6040516001600160a01b03909116815260200160405180910390f35b61004b610075366004610298565b610117565b5f8183516020850186f590506001600160a01b0381166100dd5760405162461bcd60e51b815260206004820152601960248201527810dbdd5b19081b9bdd0819195c1b1bde4818dbdb9d1c9858dd603a1b60448201526064015b60405180910390fd5b6040516001600160a01b038216907f4db17dd5e4732fb6da34a148104a592783ca119a1e7bb8829eba6cbadef0b511905f90a29392505050565b5f81516020830184f090506001600160a01b0381166101745760405162461bcd60e51b815260206004820152601960248201527810dbdd5b19081b9bdd0819195c1b1bde4818dbdb9d1c9858dd603a1b60448201526064016100d4565b6040516001600160a01b038216907f4db17dd5e4732fb6da34a148104a592783ca119a1e7bb8829eba6cbadef0b511905f90a292915050565b634e487b7160e01b5f52604160045260245ffd5b5f82601f8301126101d0575f5ffd5b813567ffffffffffffffff8111156101ea576101ea6101ad565b604051601f8201601f19908116603f0116810167ffffffffffffffff81118282101715610219576102196101ad565b604052818152838201602001851015610230575f5ffd5b816020850160208301375f918101602001919091529392505050565b5f5f5f6060848603121561025e575f5ffd5b83359250602084013567ffffffffffffffff81111561027b575f5ffd5b610287868287016101c1565b925050604084013590509250925092565b5f5f604083850312156102a9575f5ffd5b82359150602083013567ffffffffffffffff8111156102c6575f5ffd5b6102d2858286016101c1565b915050925092905056fea264697066735822122010f33bf99dbcdf7f017b7a2e5b47d0aeee24780413c75fec90c2e5fca1e9bc7664736f6c634300081c0033";

  
      type CreateCallConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: CreateCallConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class CreateCall__factory extends ContractFactory {
    
      constructor(...args: CreateCallConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<CreateCall & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): CreateCall__factory {
      return super.connect(runner) as CreateCall__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): CreateCallInterface {
      return new Interface(_abi) as CreateCallInterface;
    }
    
    override attach(address: string | Addressable): CreateCall {
      return super.attach(address) as CreateCall;
    }
  static connect(address: string, runner?: ContractRunner | null): CreateCall {
      return new Contract(address, _abi, runner) as unknown as CreateCall;
    }
  }

  
  