/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { FallbackHandler, FallbackHandlerInterface } from "../../../../handler/extensible/FallbackHandler.sol/FallbackHandler.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "contract ISafe",
        "name": "safe",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "bytes4",
        "name": "selector",
        "type": "bytes4"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "oldMethod",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "newMethod",
        "type": "bytes32"
      }
    ],
    "name": "ChangedSafeMethod",
    "type": "event"
  },
  {
    "stateMutability": "nonpayable",
    "type": "fallback"
  },
  {
    "inputs": [
      {
        "internalType": "contract ISafe",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "bytes4",
        "name": "",
        "type": "bytes4"
      }
    ],
    "name": "safeMethods",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes4",
        "name": "selector",
        "type": "bytes4"
      },
      {
        "internalType": "bytes32",
        "name": "newMethod",
        "type": "bytes32"
      }
    ],
    "name": "setSafeMethod",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class FallbackHandler__factory {
    static readonly abi = _abi;
    static createInterface(): FallbackHandlerInterface {
      return new Interface(_abi) as FallbackHandlerInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): FallbackHandler {
      return new Contract(address, _abi, runner) as unknown as FallbackHandler;
    }
  }
  