/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IFallbackHandler, IFallbackHandlerInterface } from "../../../../handler/extensible/FallbackHandler.sol/IFallbackHandler.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes4",
        "name": "selector",
        "type": "bytes4"
      },
      {
        "internalType": "bytes32",
        "name": "newMethod",
        "type": "bytes32"
      }
    ],
    "name": "setSafeMethod",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IFallbackHandler__factory {
    static readonly abi = _abi;
    static createInterface(): IFallbackHandlerInterface {
      return new Interface(_abi) as IFallbackHandlerInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IFallbackHandler {
      return new Contract(address, _abi, runner) as unknown as IFallbackHandler;
    }
  }
  