/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FallbackHandler__factory } from './FallbackHandler__factory.js';
export { IFallbackHandler__factory } from './IFallbackHandler__factory.js';