// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface SelfAuthorized$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "SelfAuthorized";
  readonly sourceName: "contracts/common/SelfAuthorized.sol";
  readonly abi: [];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/common/SelfAuthorized.sol";
  readonly buildInfoId: "solc-0_8_28-72797810d6bf4038ce7f1de6493c4b9e6004ffe3";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["SelfAuthorized"]: SelfAuthorized$Type;
    ["contracts/common/SelfAuthorized.sol:SelfAuthorized"]: SelfAuthorized$Type;
  }
}