// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface BaseTransactionGuard$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "BaseTransactionGuard";
  readonly sourceName: "contracts/base/GuardManager.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes32","name":"hash","type":"bytes32"},{"internalType":"bool","name":"success","type":"bool"}],"name":"checkAfterExecution","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"value","type":"uint256"},{"internalType":"bytes","name":"data","type":"bytes"},{"internalType":"enum Enum.Operation","name":"operation","type":"uint8"},{"internalType":"uint256","name":"safeTxGas","type":"uint256"},{"internalType":"uint256","name":"baseGas","type":"uint256"},{"internalType":"uint256","name":"gasPrice","type":"uint256"},{"internalType":"address","name":"gasToken","type":"address"},{"internalType":"address payable","name":"refundReceiver","type":"address"},{"internalType":"bytes","name":"signatures","type":"bytes"},{"internalType":"address","name":"msgSender","type":"address"}],"name":"checkTransaction","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bytes4","name":"interfaceId","type":"bytes4"}],"name":"supportsInterface","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/base/GuardManager.sol";
  readonly buildInfoId: "solc-0_8_28-908052cdd43139f36a07385062e6d6a9bbb995fc";
};

export interface GuardManager$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "GuardManager";
  readonly sourceName: "contracts/base/GuardManager.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"guard","type":"address"}],"name":"ChangedGuard","type":"event"},{"inputs":[{"internalType":"address","name":"guard","type":"address"}],"name":"setGuard","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/base/GuardManager.sol";
  readonly buildInfoId: "solc-0_8_28-908052cdd43139f36a07385062e6d6a9bbb995fc";
};

export interface ITransactionGuard$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ITransactionGuard";
  readonly sourceName: "contracts/base/GuardManager.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes32","name":"hash","type":"bytes32"},{"internalType":"bool","name":"success","type":"bool"}],"name":"checkAfterExecution","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"value","type":"uint256"},{"internalType":"bytes","name":"data","type":"bytes"},{"internalType":"enum Enum.Operation","name":"operation","type":"uint8"},{"internalType":"uint256","name":"safeTxGas","type":"uint256"},{"internalType":"uint256","name":"baseGas","type":"uint256"},{"internalType":"uint256","name":"gasPrice","type":"uint256"},{"internalType":"address","name":"gasToken","type":"address"},{"internalType":"address payable","name":"refundReceiver","type":"address"},{"internalType":"bytes","name":"signatures","type":"bytes"},{"internalType":"address","name":"msgSender","type":"address"}],"name":"checkTransaction","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bytes4","name":"interfaceId","type":"bytes4"}],"name":"supportsInterface","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/base/GuardManager.sol";
  readonly buildInfoId: "solc-0_8_28-908052cdd43139f36a07385062e6d6a9bbb995fc";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["BaseTransactionGuard"]: BaseTransactionGuard$Type
    ["GuardManager"]: GuardManager$Type
    ["ITransactionGuard"]: ITransactionGuard$Type;
    ["contracts/base/GuardManager.sol:BaseTransactionGuard"]: BaseTransactionGuard$Type
    ["contracts/base/GuardManager.sol:GuardManager"]: GuardManager$Type
    ["contracts/base/GuardManager.sol:ITransactionGuard"]: ITransactionGuard$Type;
  }
}