// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface FallbackHandler$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "FallbackHandler";
  readonly sourceName: "contracts/handler/extensible/FallbackHandler.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":true,"internalType":"contract ISafe","name":"safe","type":"address"},{"indexed":false,"internalType":"bytes4","name":"selector","type":"bytes4"},{"indexed":false,"internalType":"bytes32","name":"oldMethod","type":"bytes32"},{"indexed":false,"internalType":"bytes32","name":"newMethod","type":"bytes32"}],"name":"ChangedSafeMethod","type":"event"},{"stateMutability":"nonpayable","type":"fallback"},{"inputs":[{"internalType":"contract ISafe","name":"","type":"address"},{"internalType":"bytes4","name":"","type":"bytes4"}],"name":"safeMethods","outputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes4","name":"selector","type":"bytes4"},{"internalType":"bytes32","name":"newMethod","type":"bytes32"}],"name":"setSafeMethod","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/handler/extensible/FallbackHandler.sol";
  readonly buildInfoId: "solc-0_8_28-e204f8382dde702fbba820862f0b0422993ee5ad";
};

export interface IFallbackHandler$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IFallbackHandler";
  readonly sourceName: "contracts/handler/extensible/FallbackHandler.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes4","name":"selector","type":"bytes4"},{"internalType":"bytes32","name":"newMethod","type":"bytes32"}],"name":"setSafeMethod","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/handler/extensible/FallbackHandler.sol";
  readonly buildInfoId: "solc-0_8_28-e204f8382dde702fbba820862f0b0422993ee5ad";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["FallbackHandler"]: FallbackHandler$Type
    ["IFallbackHandler"]: IFallbackHandler$Type;
    ["contracts/handler/extensible/FallbackHandler.sol:FallbackHandler"]: FallbackHandler$Type
    ["contracts/handler/extensible/FallbackHandler.sol:IFallbackHandler"]: IFallbackHandler$Type;
  }
}