// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Singleton$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Singleton";
  readonly sourceName: "contracts/common/Singleton.sol";
  readonly abi: [];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/common/Singleton.sol";
  readonly buildInfoId: "solc-0_8_28-383e540e0632e5f3f1700d816e1788ca6de573fc";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Singleton"]: Singleton$Type;
    ["contracts/common/Singleton.sol:Singleton"]: Singleton$Type;
  }
}