// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ERC777TokensRecipient$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ERC777TokensRecipient";
  readonly sourceName: "contracts/interfaces/ERC777TokensRecipient.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"operator","type":"address"},{"internalType":"address","name":"from","type":"address"},{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"},{"internalType":"bytes","name":"data","type":"bytes"},{"internalType":"bytes","name":"operatorData","type":"bytes"}],"name":"tokensReceived","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/ERC777TokensRecipient.sol";
  readonly buildInfoId: "solc-0_8_28-ed2d128c3ac1e98a551cdd21051ecbf6dd081352";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ERC777TokensRecipient"]: ERC777TokensRecipient$Type;
    ["contracts/interfaces/ERC777TokensRecipient.sol:ERC777TokensRecipient"]: ERC777TokensRecipient$Type;
  }
}