/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../common.js"
  import type { MultiSend, MultiSendInterface } from "../../../libraries/MultiSend.sol/MultiSend.js";

  const _abi = [
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "transactions",
        "type": "bytes"
      }
    ],
    "name": "multiSend",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x60a0604052348015600e575f5ffd5b503060805260805161025a61002a5f395f6040015261025a5ff3fe60806040526004361061001d575f3560e01c80638d80ff0a14610021575b5f5ffd5b61003461002f366004610171565b610036565b005b6001600160a01b037f00000000000000000000000000000000000000000000000000000000000000001630036100cb5760405162461bcd60e51b815260206004820152603060248201527f4d756c746953656e642073686f756c64206f6e6c792062652063616c6c65642060448201526f1d9a584819195b1959d85d1958d85b1b60821b606482015260840160405180910390fd5b805160205b8181101561015857828101805160018201516015830151603584015160f89390931c9360609290921c80153002179290916055015f858015610119576001811461012857610132565b5f5f8585888a5af19150610132565b5f5f8585895af491505b50806101455760405195503d5f873e3d86fd5b50508060550185019450505050506100d0565b505050565b634e487b7160e01b5f52604160045260245ffd5b5f60208284031215610181575f5ffd5b813567ffffffffffffffff811115610197575f5ffd5b8201601f810184136101a7575f5ffd5b803567ffffffffffffffff8111156101c1576101c161015d565b604051601f8201601f19908116603f0116810167ffffffffffffffff811182821017156101f0576101f061015d565b604052818152828201602001861015610207575f5ffd5b816020840160208301375f9181016020019190915294935050505056fea2646970667358221220b58bb78a5d72b8ca0cf5dc7438333379f8afbf083bab570b6b75c1198487a5a664736f6c634300081c0033";

  
      type MultiSendConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MultiSendConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MultiSend__factory extends ContractFactory {
    
      constructor(...args: MultiSendConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MultiSend & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MultiSend__factory {
      return super.connect(runner) as MultiSend__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MultiSendInterface {
      return new Interface(_abi) as MultiSendInterface;
    }
    
    override attach(address: string | Addressable): MultiSend {
      return super.attach(address) as MultiSend;
    }
  static connect(address: string, runner?: ContractRunner | null): MultiSend {
      return new Contract(address, _abi, runner) as unknown as MultiSend;
    }
  }

  
  