// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Enum$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Enum";
  readonly sourceName: "contracts/libraries/Enum.sol";
  readonly abi: [];
  readonly bytecode: "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220b2a8f9d285c0bca4a2ea1e56a5b93e7eff0597ec46ee48d9284baaea68aa839d64736f6c634300081c0033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220b2a8f9d285c0bca4a2ea1e56a5b93e7eff0597ec46ee48d9284baaea68aa839d64736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/Enum.sol";
  readonly buildInfoId: "solc-0_8_28-ed2d128c3ac1e98a551cdd21051ecbf6dd081352";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Enum"]: Enum$Type;
    ["contracts/libraries/Enum.sol:Enum"]: Enum$Type;
  }
}