// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Enum$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Enum";
  readonly sourceName: "contracts/libraries/Enum.sol";
  readonly abi: [];
  readonly bytecode: "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212209a3a3e74fe45c781392eb16dbfbe3f4098385608aa1d27483c0712708db82b1264736f6c634300081c0033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212209a3a3e74fe45c781392eb16dbfbe3f4098385608aa1d27483c0712708db82b1264736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/Enum.sol";
  readonly buildInfoId: "solc-0_8_28-601792ff4342a9c34db206f2c04cfbc09c2545f4";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Enum"]: Enum$Type;
    ["contracts/libraries/Enum.sol:Enum"]: Enum$Type;
  }
}