/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IStorageAccessible, IStorageAccessibleInterface } from "../../../interfaces/IStorageAccessible.sol/IStorageAccessible.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "offset",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "length",
        "type": "uint256"
      }
    ],
    "name": "getStorageAt",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "targetContract",
        "type": "address"
      },
      {
        "internalType": "bytes",
        "name": "calldataPayload",
        "type": "bytes"
      }
    ],
    "name": "simulateAndRevert",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IStorageAccessible__factory {
    static readonly abi = _abi;
    static createInterface(): IStorageAccessibleInterface {
      return new Interface(_abi) as IStorageAccessibleInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IStorageAccessible {
      return new Contract(address, _abi, runner) as unknown as IStorageAccessible;
    }
  }
  