/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc1155TokenReceiverSol from './ERC1155TokenReceiver.sol/index.js';
export type { erc1155TokenReceiverSol };
import type * as erc721TokenReceiverSol from './ERC721TokenReceiver.sol/index.js';
export type { erc721TokenReceiverSol };
import type * as erc777TokensRecipientSol from './ERC777TokensRecipient.sol/index.js';
export type { erc777TokensRecipientSol };
import type * as ierc165Sol from './IERC165.sol/index.js';
export type { ierc165Sol };
import type * as iFallbackManagerSol from './IFallbackManager.sol/index.js';
export type { iFallbackManagerSol };
import type * as iGuardManagerSol from './IGuardManager.sol/index.js';
export type { iGuardManagerSol };
import type * as iModuleManagerSol from './IModuleManager.sol/index.js';
export type { iModuleManagerSol };
import type * as iNativeCurrencyPaymentFallbackSol from './INativeCurrencyPaymentFallback.sol/index.js';
export type { iNativeCurrencyPaymentFallbackSol };
import type * as iOwnerManagerSol from './IOwnerManager.sol/index.js';
export type { iOwnerManagerSol };
import type * as iSafeSol from './ISafe.sol/index.js';
export type { iSafeSol };
import type * as iSignatureValidatorSol from './ISignatureValidator.sol/index.js';
export type { iSignatureValidatorSol };
import type * as iStorageAccessibleSol from './IStorageAccessible.sol/index.js';
export type { iStorageAccessibleSol };
import type * as viewStorageAccessibleSol from './ViewStorageAccessible.sol/index.js';
export type { viewStorageAccessibleSol };