// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ExtensibleBase$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ExtensibleBase";
  readonly sourceName: "contracts/handler/extensible/ExtensibleBase.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":true,"internalType":"contract ISafe","name":"safe","type":"address"},{"indexed":false,"internalType":"bytes4","name":"selector","type":"bytes4"},{"indexed":false,"internalType":"bytes32","name":"oldMethod","type":"bytes32"},{"indexed":false,"internalType":"bytes32","name":"newMethod","type":"bytes32"}],"name":"ChangedSafeMethod","type":"event"},{"inputs":[{"internalType":"contract ISafe","name":"","type":"address"},{"internalType":"bytes4","name":"","type":"bytes4"}],"name":"safeMethods","outputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/handler/extensible/ExtensibleBase.sol";
  readonly buildInfoId: "solc-0_8_28-01a07801a84c920c217ca94ad8d8b240dffdb2bb";
};

export interface IFallbackMethod$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IFallbackMethod";
  readonly sourceName: "contracts/handler/extensible/ExtensibleBase.sol";
  readonly abi: [{"inputs":[{"internalType":"contract ISafe","name":"safe","type":"address"},{"internalType":"address","name":"sender","type":"address"},{"internalType":"uint256","name":"value","type":"uint256"},{"internalType":"bytes","name":"data","type":"bytes"}],"name":"handle","outputs":[{"internalType":"bytes","name":"result","type":"bytes"}],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/handler/extensible/ExtensibleBase.sol";
  readonly buildInfoId: "solc-0_8_28-01a07801a84c920c217ca94ad8d8b240dffdb2bb";
};

export interface IStaticFallbackMethod$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IStaticFallbackMethod";
  readonly sourceName: "contracts/handler/extensible/ExtensibleBase.sol";
  readonly abi: [{"inputs":[{"internalType":"contract ISafe","name":"safe","type":"address"},{"internalType":"address","name":"sender","type":"address"},{"internalType":"uint256","name":"value","type":"uint256"},{"internalType":"bytes","name":"data","type":"bytes"}],"name":"handle","outputs":[{"internalType":"bytes","name":"result","type":"bytes"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/handler/extensible/ExtensibleBase.sol";
  readonly buildInfoId: "solc-0_8_28-01a07801a84c920c217ca94ad8d8b240dffdb2bb";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ExtensibleBase"]: ExtensibleBase$Type
    ["IFallbackMethod"]: IFallbackMethod$Type
    ["IStaticFallbackMethod"]: IStaticFallbackMethod$Type;
    ["contracts/handler/extensible/ExtensibleBase.sol:ExtensibleBase"]: ExtensibleBase$Type
    ["contracts/handler/extensible/ExtensibleBase.sol:IFallbackMethod"]: IFallbackMethod$Type
    ["contracts/handler/extensible/ExtensibleBase.sol:IStaticFallbackMethod"]: IStaticFallbackMethod$Type;
  }
}