/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'SimulateTxAccessor', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SimulateTxAccessor__factory>
getContractFactory(name: 'FallbackManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.FallbackManager__factory>
getContractFactory(name: 'BaseTransactionGuard', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BaseTransactionGuard__factory>
getContractFactory(name: 'GuardManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.GuardManager__factory>
getContractFactory(name: 'ITransactionGuard', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ITransactionGuard__factory>
getContractFactory(name: 'BaseModuleGuard', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BaseModuleGuard__factory>
getContractFactory(name: 'IModuleGuard', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IModuleGuard__factory>
getContractFactory(name: 'ModuleManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ModuleManager__factory>
getContractFactory(name: 'OwnerManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.OwnerManager__factory>
getContractFactory(name: 'NativeCurrencyPaymentFallback', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.NativeCurrencyPaymentFallback__factory>
getContractFactory(name: 'StorageAccessible', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.StorageAccessible__factory>
getContractFactory(name: 'BaseGuard', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BaseGuard__factory>
getContractFactory(name: 'DebugTransactionGuard', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.DebugTransactionGuard__factory>
getContractFactory(name: 'DelegateCallTransactionGuard', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.DelegateCallTransactionGuard__factory>
getContractFactory(name: 'OnlyOwnersGuard', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.OnlyOwnersGuard__factory>
getContractFactory(name: 'ReentrancyTransactionGuard', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ReentrancyTransactionGuard__factory>
getContractFactory(name: 'Migration', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Migration__factory>
getContractFactory(name: 'CompatibilityFallbackHandler', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CompatibilityFallbackHandler__factory>
getContractFactory(name: 'ERC165Handler', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ERC165Handler__factory>
getContractFactory(name: 'IERC165Handler', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC165Handler__factory>
getContractFactory(name: 'ExtensibleBase', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ExtensibleBase__factory>
getContractFactory(name: 'IFallbackMethod', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IFallbackMethod__factory>
getContractFactory(name: 'IStaticFallbackMethod', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IStaticFallbackMethod__factory>
getContractFactory(name: 'FallbackHandler', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.FallbackHandler__factory>
getContractFactory(name: 'IFallbackHandler', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IFallbackHandler__factory>
getContractFactory(name: 'ERC1271', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ERC1271__factory>
getContractFactory(name: 'ISafeSignatureVerifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ISafeSignatureVerifier__factory>
getContractFactory(name: 'ISignatureVerifierMuxer', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ISignatureVerifierMuxer__factory>
getContractFactory(name: 'SignatureVerifierMuxer', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SignatureVerifierMuxer__factory>
getContractFactory(name: 'TokenCallbacks', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TokenCallbacks__factory>
getContractFactory(name: 'ExtensibleFallbackHandler', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ExtensibleFallbackHandler__factory>
getContractFactory(name: 'TokenCallbackHandler', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TokenCallbackHandler__factory>
getContractFactory(name: 'ERC1155TokenReceiver', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ERC1155TokenReceiver__factory>
getContractFactory(name: 'ERC721TokenReceiver', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ERC721TokenReceiver__factory>
getContractFactory(name: 'ERC777TokensRecipient', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ERC777TokensRecipient__factory>
getContractFactory(name: 'IERC165', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC165__factory>
getContractFactory(name: 'IFallbackManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IFallbackManager__factory>
getContractFactory(name: 'IGuardManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IGuardManager__factory>
getContractFactory(name: 'IModuleManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IModuleManager__factory>
getContractFactory(name: 'INativeCurrencyPaymentFallback', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.INativeCurrencyPaymentFallback__factory>
getContractFactory(name: 'IOwnerManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IOwnerManager__factory>
getContractFactory(name: 'ISafe', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ISafe__factory>
getContractFactory(name: 'ISignatureValidator', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ISignatureValidator__factory>
getContractFactory(name: 'IStorageAccessible', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IStorageAccessible__factory>
getContractFactory(name: 'ViewStorageAccessible', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ViewStorageAccessible__factory>
getContractFactory(name: 'CreateCall', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CreateCall__factory>
getContractFactory(name: 'MultiSend', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MultiSend__factory>
getContractFactory(name: 'MultiSendCallOnly', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MultiSendCallOnly__factory>
getContractFactory(name: 'SafeMigration', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SafeMigration__factory>
getContractFactory(name: 'SafeToL2Setup', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SafeToL2Setup__factory>
getContractFactory(name: 'SignMessageLib', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SignMessageLib__factory>
getContractFactory(name: 'IProxy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IProxy__factory>
getContractFactory(name: 'SafeProxy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SafeProxy__factory>
getContractFactory(name: 'SafeProxyFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SafeProxyFactory__factory>
getContractFactory(name: 'Safe', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Safe__factory>
getContractFactory(name: 'SafeL2', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SafeL2__factory>
getContractFactory(name: 'SimpleGuard', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SimpleGuard__factory>
getContractFactory(name: 'SingletonFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SingletonFactory__factory>

  getContractAt(name: 'SimulateTxAccessor', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SimulateTxAccessor>
getContractAt(name: 'FallbackManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.FallbackManager>
getContractAt(name: 'BaseTransactionGuard', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BaseTransactionGuard>
getContractAt(name: 'GuardManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.GuardManager>
getContractAt(name: 'ITransactionGuard', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ITransactionGuard>
getContractAt(name: 'BaseModuleGuard', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BaseModuleGuard>
getContractAt(name: 'IModuleGuard', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IModuleGuard>
getContractAt(name: 'ModuleManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ModuleManager>
getContractAt(name: 'OwnerManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.OwnerManager>
getContractAt(name: 'NativeCurrencyPaymentFallback', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.NativeCurrencyPaymentFallback>
getContractAt(name: 'StorageAccessible', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.StorageAccessible>
getContractAt(name: 'BaseGuard', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BaseGuard>
getContractAt(name: 'DebugTransactionGuard', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.DebugTransactionGuard>
getContractAt(name: 'DelegateCallTransactionGuard', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.DelegateCallTransactionGuard>
getContractAt(name: 'OnlyOwnersGuard', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.OnlyOwnersGuard>
getContractAt(name: 'ReentrancyTransactionGuard', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ReentrancyTransactionGuard>
getContractAt(name: 'Migration', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Migration>
getContractAt(name: 'CompatibilityFallbackHandler', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CompatibilityFallbackHandler>
getContractAt(name: 'ERC165Handler', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ERC165Handler>
getContractAt(name: 'IERC165Handler', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC165Handler>
getContractAt(name: 'ExtensibleBase', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ExtensibleBase>
getContractAt(name: 'IFallbackMethod', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IFallbackMethod>
getContractAt(name: 'IStaticFallbackMethod', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IStaticFallbackMethod>
getContractAt(name: 'FallbackHandler', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.FallbackHandler>
getContractAt(name: 'IFallbackHandler', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IFallbackHandler>
getContractAt(name: 'ERC1271', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ERC1271>
getContractAt(name: 'ISafeSignatureVerifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ISafeSignatureVerifier>
getContractAt(name: 'ISignatureVerifierMuxer', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ISignatureVerifierMuxer>
getContractAt(name: 'SignatureVerifierMuxer', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SignatureVerifierMuxer>
getContractAt(name: 'TokenCallbacks', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TokenCallbacks>
getContractAt(name: 'ExtensibleFallbackHandler', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ExtensibleFallbackHandler>
getContractAt(name: 'TokenCallbackHandler', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TokenCallbackHandler>
getContractAt(name: 'ERC1155TokenReceiver', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ERC1155TokenReceiver>
getContractAt(name: 'ERC721TokenReceiver', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ERC721TokenReceiver>
getContractAt(name: 'ERC777TokensRecipient', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ERC777TokensRecipient>
getContractAt(name: 'IERC165', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC165>
getContractAt(name: 'IFallbackManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IFallbackManager>
getContractAt(name: 'IGuardManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IGuardManager>
getContractAt(name: 'IModuleManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IModuleManager>
getContractAt(name: 'INativeCurrencyPaymentFallback', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.INativeCurrencyPaymentFallback>
getContractAt(name: 'IOwnerManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IOwnerManager>
getContractAt(name: 'ISafe', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ISafe>
getContractAt(name: 'ISignatureValidator', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ISignatureValidator>
getContractAt(name: 'IStorageAccessible', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IStorageAccessible>
getContractAt(name: 'ViewStorageAccessible', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ViewStorageAccessible>
getContractAt(name: 'CreateCall', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CreateCall>
getContractAt(name: 'MultiSend', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MultiSend>
getContractAt(name: 'MultiSendCallOnly', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MultiSendCallOnly>
getContractAt(name: 'SafeMigration', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SafeMigration>
getContractAt(name: 'SafeToL2Setup', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SafeToL2Setup>
getContractAt(name: 'SignMessageLib', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SignMessageLib>
getContractAt(name: 'IProxy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IProxy>
getContractAt(name: 'SafeProxy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SafeProxy>
getContractAt(name: 'SafeProxyFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SafeProxyFactory>
getContractAt(name: 'Safe', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Safe>
getContractAt(name: 'SafeL2', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SafeL2>
getContractAt(name: 'SimpleGuard', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SimpleGuard>
getContractAt(name: 'SingletonFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SingletonFactory>

  deployContract(name: 'SimulateTxAccessor', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimulateTxAccessor>
deployContract(name: 'FallbackManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FallbackManager>
deployContract(name: 'BaseTransactionGuard', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BaseTransactionGuard>
deployContract(name: 'GuardManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GuardManager>
deployContract(name: 'ITransactionGuard', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITransactionGuard>
deployContract(name: 'BaseModuleGuard', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BaseModuleGuard>
deployContract(name: 'IModuleGuard', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IModuleGuard>
deployContract(name: 'ModuleManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ModuleManager>
deployContract(name: 'OwnerManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OwnerManager>
deployContract(name: 'NativeCurrencyPaymentFallback', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NativeCurrencyPaymentFallback>
deployContract(name: 'StorageAccessible', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.StorageAccessible>
deployContract(name: 'BaseGuard', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BaseGuard>
deployContract(name: 'DebugTransactionGuard', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DebugTransactionGuard>
deployContract(name: 'DelegateCallTransactionGuard', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DelegateCallTransactionGuard>
deployContract(name: 'OnlyOwnersGuard', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OnlyOwnersGuard>
deployContract(name: 'ReentrancyTransactionGuard', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ReentrancyTransactionGuard>
deployContract(name: 'Migration', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Migration>
deployContract(name: 'CompatibilityFallbackHandler', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CompatibilityFallbackHandler>
deployContract(name: 'ERC165Handler', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC165Handler>
deployContract(name: 'IERC165Handler', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC165Handler>
deployContract(name: 'ExtensibleBase', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ExtensibleBase>
deployContract(name: 'IFallbackMethod', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IFallbackMethod>
deployContract(name: 'IStaticFallbackMethod', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStaticFallbackMethod>
deployContract(name: 'FallbackHandler', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FallbackHandler>
deployContract(name: 'IFallbackHandler', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IFallbackHandler>
deployContract(name: 'ERC1271', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC1271>
deployContract(name: 'ISafeSignatureVerifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISafeSignatureVerifier>
deployContract(name: 'ISignatureVerifierMuxer', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISignatureVerifierMuxer>
deployContract(name: 'SignatureVerifierMuxer', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SignatureVerifierMuxer>
deployContract(name: 'TokenCallbacks', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TokenCallbacks>
deployContract(name: 'ExtensibleFallbackHandler', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ExtensibleFallbackHandler>
deployContract(name: 'TokenCallbackHandler', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TokenCallbackHandler>
deployContract(name: 'ERC1155TokenReceiver', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC1155TokenReceiver>
deployContract(name: 'ERC721TokenReceiver', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC721TokenReceiver>
deployContract(name: 'ERC777TokensRecipient', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC777TokensRecipient>
deployContract(name: 'IERC165', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC165>
deployContract(name: 'IFallbackManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IFallbackManager>
deployContract(name: 'IGuardManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IGuardManager>
deployContract(name: 'IModuleManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IModuleManager>
deployContract(name: 'INativeCurrencyPaymentFallback', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INativeCurrencyPaymentFallback>
deployContract(name: 'IOwnerManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IOwnerManager>
deployContract(name: 'ISafe', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISafe>
deployContract(name: 'ISignatureValidator', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISignatureValidator>
deployContract(name: 'IStorageAccessible', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStorageAccessible>
deployContract(name: 'ViewStorageAccessible', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ViewStorageAccessible>
deployContract(name: 'CreateCall', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CreateCall>
deployContract(name: 'MultiSend', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MultiSend>
deployContract(name: 'MultiSendCallOnly', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MultiSendCallOnly>
deployContract(name: 'SafeMigration', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SafeMigration>
deployContract(name: 'SafeToL2Setup', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SafeToL2Setup>
deployContract(name: 'SignMessageLib', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SignMessageLib>
deployContract(name: 'IProxy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IProxy>
deployContract(name: 'SafeProxy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SafeProxy>
deployContract(name: 'SafeProxyFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SafeProxyFactory>
deployContract(name: 'Safe', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Safe>
deployContract(name: 'SafeL2', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SafeL2>
deployContract(name: 'SimpleGuard', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimpleGuard>
deployContract(name: 'SingletonFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SingletonFactory>

  deployContract(name: 'SimulateTxAccessor', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimulateTxAccessor>
deployContract(name: 'FallbackManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FallbackManager>
deployContract(name: 'BaseTransactionGuard', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BaseTransactionGuard>
deployContract(name: 'GuardManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GuardManager>
deployContract(name: 'ITransactionGuard', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITransactionGuard>
deployContract(name: 'BaseModuleGuard', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BaseModuleGuard>
deployContract(name: 'IModuleGuard', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IModuleGuard>
deployContract(name: 'ModuleManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ModuleManager>
deployContract(name: 'OwnerManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OwnerManager>
deployContract(name: 'NativeCurrencyPaymentFallback', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NativeCurrencyPaymentFallback>
deployContract(name: 'StorageAccessible', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.StorageAccessible>
deployContract(name: 'BaseGuard', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BaseGuard>
deployContract(name: 'DebugTransactionGuard', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DebugTransactionGuard>
deployContract(name: 'DelegateCallTransactionGuard', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DelegateCallTransactionGuard>
deployContract(name: 'OnlyOwnersGuard', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OnlyOwnersGuard>
deployContract(name: 'ReentrancyTransactionGuard', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ReentrancyTransactionGuard>
deployContract(name: 'Migration', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Migration>
deployContract(name: 'CompatibilityFallbackHandler', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CompatibilityFallbackHandler>
deployContract(name: 'ERC165Handler', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC165Handler>
deployContract(name: 'IERC165Handler', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC165Handler>
deployContract(name: 'ExtensibleBase', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ExtensibleBase>
deployContract(name: 'IFallbackMethod', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IFallbackMethod>
deployContract(name: 'IStaticFallbackMethod', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStaticFallbackMethod>
deployContract(name: 'FallbackHandler', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FallbackHandler>
deployContract(name: 'IFallbackHandler', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IFallbackHandler>
deployContract(name: 'ERC1271', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC1271>
deployContract(name: 'ISafeSignatureVerifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISafeSignatureVerifier>
deployContract(name: 'ISignatureVerifierMuxer', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISignatureVerifierMuxer>
deployContract(name: 'SignatureVerifierMuxer', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SignatureVerifierMuxer>
deployContract(name: 'TokenCallbacks', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TokenCallbacks>
deployContract(name: 'ExtensibleFallbackHandler', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ExtensibleFallbackHandler>
deployContract(name: 'TokenCallbackHandler', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TokenCallbackHandler>
deployContract(name: 'ERC1155TokenReceiver', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC1155TokenReceiver>
deployContract(name: 'ERC721TokenReceiver', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC721TokenReceiver>
deployContract(name: 'ERC777TokensRecipient', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC777TokensRecipient>
deployContract(name: 'IERC165', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC165>
deployContract(name: 'IFallbackManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IFallbackManager>
deployContract(name: 'IGuardManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IGuardManager>
deployContract(name: 'IModuleManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IModuleManager>
deployContract(name: 'INativeCurrencyPaymentFallback', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INativeCurrencyPaymentFallback>
deployContract(name: 'IOwnerManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IOwnerManager>
deployContract(name: 'ISafe', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISafe>
deployContract(name: 'ISignatureValidator', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISignatureValidator>
deployContract(name: 'IStorageAccessible', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStorageAccessible>
deployContract(name: 'ViewStorageAccessible', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ViewStorageAccessible>
deployContract(name: 'CreateCall', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CreateCall>
deployContract(name: 'MultiSend', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MultiSend>
deployContract(name: 'MultiSendCallOnly', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MultiSendCallOnly>
deployContract(name: 'SafeMigration', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SafeMigration>
deployContract(name: 'SafeToL2Setup', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SafeToL2Setup>
deployContract(name: 'SignMessageLib', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SignMessageLib>
deployContract(name: 'IProxy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IProxy>
deployContract(name: 'SafeProxy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SafeProxy>
deployContract(name: 'SafeProxyFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SafeProxyFactory>
deployContract(name: 'Safe', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Safe>
deployContract(name: 'SafeL2', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SafeL2>
deployContract(name: 'SimpleGuard', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimpleGuard>
deployContract(name: 'SingletonFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SingletonFactory>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  