// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ViewStorageAccessible$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ViewStorageAccessible";
  readonly sourceName: "contracts/interfaces/ViewStorageAccessible.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"targetContract","type":"address"},{"internalType":"bytes","name":"calldataPayload","type":"bytes"}],"name":"simulate","outputs":[{"internalType":"bytes","name":"","type":"bytes"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/ViewStorageAccessible.sol";
  readonly buildInfoId: "solc-0_8_28-1a48c6503cd4ad61e30d1607d7aae354a055d21b";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ViewStorageAccessible"]: ViewStorageAccessible$Type;
    ["contracts/interfaces/ViewStorageAccessible.sol:ViewStorageAccessible"]: ViewStorageAccessible$Type;
  }
}