// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IProxy$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IProxy";
  readonly sourceName: "contracts/proxies/SafeProxy.sol";
  readonly abi: [{"inputs":[],"name":"masterCopy","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/proxies/SafeProxy.sol";
  readonly buildInfoId: "solc-0_8_28-54f0abea0b4a99a1b8da8c0a9da21029151d1d49";
};

export interface SafeProxy$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "SafeProxy";
  readonly sourceName: "contracts/proxies/SafeProxy.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"_singleton","type":"address"}],"stateMutability":"nonpayable","type":"constructor"},{"stateMutability":"payable","type":"fallback"}];
  readonly bytecode: "0x6080604052348015600e575f5ffd5b5060405161015e38038061015e833981016040819052602b9160b2565b6001600160a01b038116608f5760405162461bcd60e51b815260206004820152602260248201527f496e76616c69642073696e676c65746f6e20616464726573732070726f766964604482015261195960f21b606482015260840160405180910390fd5b5f80546001600160a01b0319166001600160a01b039290921691909117905560dd565b5f6020828403121560c1575f5ffd5b81516001600160a01b038116811460d6575f5ffd5b9392505050565b6075806100e95f395ff3fe60806040525f5463a619486e5f3560e01c036021578060601b606c5260206060f35b365f5f375f5f365f845af490503d5f5f3e80603a573d5ffd5b503d5ff3fea2646970667358221220581452328d0713ff79e978fa8d6275a5fecf2d28d063be3f86e3742ba19ea05264736f6c634300081c0033";
  readonly deployedBytecode: "0x60806040525f5463a619486e5f3560e01c036021578060601b606c5260206060f35b365f5f375f5f365f845af490503d5f5f3e80603a573d5ffd5b503d5ff3fea2646970667358221220581452328d0713ff79e978fa8d6275a5fecf2d28d063be3f86e3742ba19ea05264736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/proxies/SafeProxy.sol";
  readonly buildInfoId: "solc-0_8_28-54f0abea0b4a99a1b8da8c0a9da21029151d1d49";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IProxy"]: IProxy$Type
    ["SafeProxy"]: SafeProxy$Type;
    ["contracts/proxies/SafeProxy.sol:IProxy"]: IProxy$Type
    ["contracts/proxies/SafeProxy.sol:SafeProxy"]: SafeProxy$Type;
  }
}