/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as safeProxySol from './SafeProxy.sol/index.js';
export * as safeProxyFactorySol from './SafeProxyFactory.sol/index.js';