/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../common.js"
  import type { SignMessageLib, SignMessageLibInterface } from "../../../libraries/SignMessageLib.sol/SignMessageLib.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "msgHash",
        "type": "bytes32"
      }
    ],
    "name": "SignMsg",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "message",
        "type": "bytes"
      }
    ],
    "name": "getMessageHash",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "_data",
        "type": "bytes"
      }
    ],
    "name": "signMessage",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b506103828061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610034575f3560e01c80630a1028c41461003857806385a5affe1461005d575b5f5ffd5b61004b610046366004610214565b610072565b60405190815260200160405180910390f35b61007061006b3660046102c7565b610180565b005b5f5f7f60b3cbf8b4a223d68d641b3b6ddf9a298e7f33710cf3d3a9d1146b5a6150fbca5f1b83805190602001206040516020016100b9929190918252602082015260400190565b60408051601f19818403018152828252805160209182012063f698da2560e01b84529151919350601960f81b92600160f81b92309263f698da2592600480820193918290030181865afa158015610112573d5f5f3e3d5ffd5b505050506040513d601f19601f820116820180604052508101906101369190610335565b6040516001600160f81b0319938416602082015292909116602183015260228201526042810182905260620160405160208183030381529060405280519060200120915050919050565b5f6101bf83838080601f0160208091040260200160405190810160405280939291908181526020018383808284375f9201919091525061007292505050565b5f81815260076020526040808220600190555191925082917fe7f4675038f4f6034dfcbbb24c4dc08e4ebf10eb9d257d3d02c0f38d122ac6e49190a2505050565b634e487b7160e01b5f52604160045260245ffd5b5f60208284031215610224575f5ffd5b813567ffffffffffffffff81111561023a575f5ffd5b8201601f8101841361024a575f5ffd5b803567ffffffffffffffff81111561026457610264610200565b604051601f8201601f19908116603f0116810167ffffffffffffffff8111828210171561029357610293610200565b6040528181528282016020018610156102aa575f5ffd5b816020840160208301375f91810160200191909152949350505050565b5f5f602083850312156102d8575f5ffd5b823567ffffffffffffffff8111156102ee575f5ffd5b8301601f810185136102fe575f5ffd5b803567ffffffffffffffff811115610314575f5ffd5b856020828401011115610325575f5ffd5b6020919091019590945092505050565b5f60208284031215610345575f5ffd5b505191905056fea26469706673582212201dc60a840e58d6f2575a06f4ccd0529e187280fa5c452070a7cfb578b4ff622964736f6c634300081c0033";

  
      type SignMessageLibConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: SignMessageLibConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class SignMessageLib__factory extends ContractFactory {
    
      constructor(...args: SignMessageLibConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<SignMessageLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): SignMessageLib__factory {
      return super.connect(runner) as SignMessageLib__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): SignMessageLibInterface {
      return new Interface(_abi) as SignMessageLibInterface;
    }
    
    override attach(address: string | Addressable): SignMessageLib {
      return super.attach(address) as SignMessageLib;
    }
  static connect(address: string, runner?: ContractRunner | null): SignMessageLib {
      return new Contract(address, _abi, runner) as unknown as SignMessageLib;
    }
  }

  
  