/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fallbackManagerSol from './FallbackManager.sol/index.js';
export type { fallbackManagerSol };
import type * as guardManagerSol from './GuardManager.sol/index.js';
export type { guardManagerSol };
import type * as moduleManagerSol from './ModuleManager.sol/index.js';
export type { moduleManagerSol };
import type * as ownerManagerSol from './OwnerManager.sol/index.js';
export type { ownerManagerSol };