// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Executor$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Executor";
  readonly sourceName: "contracts/base/Executor.sol";
  readonly abi: [];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/base/Executor.sol";
  readonly buildInfoId: "solc-0_8_28-26035aa590d4f530fab9230925c8ce2f08e8e6eb";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Executor"]: Executor$Type;
    ["contracts/base/Executor.sol:Executor"]: Executor$Type;
  }
}