// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ERC721TokenReceiver$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ERC721TokenReceiver";
  readonly sourceName: "contracts/interfaces/ERC721TokenReceiver.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"_operator","type":"address"},{"internalType":"address","name":"_from","type":"address"},{"internalType":"uint256","name":"_tokenId","type":"uint256"},{"internalType":"bytes","name":"_data","type":"bytes"}],"name":"onERC721Received","outputs":[{"internalType":"bytes4","name":"","type":"bytes4"}],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/ERC721TokenReceiver.sol";
  readonly buildInfoId: "solc-0_8_28-ed2d128c3ac1e98a551cdd21051ecbf6dd081352";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ERC721TokenReceiver"]: ERC721TokenReceiver$Type;
    ["contracts/interfaces/ERC721TokenReceiver.sol:ERC721TokenReceiver"]: ERC721TokenReceiver$Type;
  }
}