/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, AddressLike, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../../common.js"
  import type { Migration, MigrationInterface } from "../../../../examples/libraries/Migrate_1_3_0_to_1_2_0.sol/Migration.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "targetSingleton",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "address",
        "name": "singleton",
        "type": "address"
      }
    ],
    "name": "ChangedMasterCopy",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "MIGRATION_SINGLETON",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "SAFE_120_SINGLETON",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "migrate",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x60c060405234801561000f575f5ffd5b5060405161034838038061034883398101604081905261002e916100a8565b6001600160a01b0381166100935760405162461bcd60e51b815260206004820152602260248201527f496e76616c69642073696e676c65746f6e20616464726573732070726f766964604482015261195960f21b606482015260840160405180910390fd5b6001600160a01b031660a052306080526100d5565b5f602082840312156100b8575f5ffd5b81516001600160a01b03811681146100ce575f5ffd5b9392505050565b60805160a0516102476101015f395f81816048015261015b01525f8181608b015260c101526102475ff3fe608060405234801561000f575f5ffd5b506004361061003f575f3560e01c806310dfd5061461004357806372f7a956146100865780638fd3ab80146100ad575b5f5ffd5b61006a7f000000000000000000000000000000000000000000000000000000000000000081565b6040516001600160a01b03909116815260200160405180910390f35b61006a7f000000000000000000000000000000000000000000000000000000000000000081565b6100b56100b7565b005b6001600160a01b037f000000000000000000000000000000000000000000000000000000000000000016300361014c5760405162461bcd60e51b815260206004820152603060248201527f4d6967726174696f6e2073686f756c64206f6e6c792062652063616c6c65642060448201526f1d9a584819195b1959d85d1958d85b1b60821b606482015260840160405180910390fd5b5f80546001600160a01b0319167f00000000000000000000000000000000000000000000000000000000000000006001600160a01b0316179055604080517f035aff83d86937d35b32e04f0ddc6ff469290eef2f1b692d8a815c89404d47496020820152309181019190915260600160408051808303601f190181529082905280516020918201206006555f546001600160a01b031682527f75e41bc35ff1bf14d81d1d2f649c0084a0f974f9289c803ec9898eeec4c8d0b8910160405180910390a156fea264697066735822122031d4f5cd23de2547f3e4e5304833c335b9b6d6c7fe91f53beae7996d5e36f96764736f6c634300081c0033";

  
      type MigrationConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MigrationConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class Migration__factory extends ContractFactory {
    
      constructor(...args: MigrationConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(targetSingleton: AddressLike, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(targetSingleton, overrides || {});
    };
    override deploy(targetSingleton: AddressLike, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(targetSingleton, overrides || {}) as Promise<Migration & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): Migration__factory {
      return super.connect(runner) as Migration__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MigrationInterface {
      return new Interface(_abi) as MigrationInterface;
    }
    
    override attach(address: string | Addressable): Migration {
      return super.attach(address) as Migration;
    }
  static connect(address: string, runner?: ContractRunner | null): Migration {
      return new Contract(address, _abi, runner) as unknown as Migration;
    }
  }

  
  