/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC165Handler } from './ERC165Handler.js';
export type { IERC165Handler } from './IERC165Handler.js';