/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { SingletonFactory, SingletonFactoryInterface } from "../../SingletonFactory.sol/SingletonFactory.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "createdContracts",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "_initCode",
        "type": "bytes"
      },
      {
        "internalType": "bytes32",
        "name": "_salt",
        "type": "bytes32"
      }
    ],
    "name": "deploy",
    "outputs": [
      {
        "internalType": "address payable",
        "name": "createdContract",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b5061020f8061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610034575f3560e01c806308811397146100385780634af63f0214610067575b5f5ffd5b61004b6100463660046100f9565b61007a565b6040516001600160a01b03909116815260200160405180910390f35b61004b610075366004610124565b6100a1565b5f8181548110610088575f80fd5b5f918252602090912001546001600160a01b0316905081565b5f818351602085015ff55f80546001810182559080527f290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e5630180546001600160a01b0319166001600160a01b0383161790559392505050565b5f60208284031215610109575f5ffd5b5035919050565b634e487b7160e01b5f52604160045260245ffd5b5f5f60408385031215610135575f5ffd5b823567ffffffffffffffff81111561014b575f5ffd5b8301601f8101851361015b575f5ffd5b803567ffffffffffffffff81111561017557610175610110565b604051601f8201601f19908116603f0116810167ffffffffffffffff811182821017156101a4576101a4610110565b6040528181528282016020018710156101bb575f5ffd5b816020840160208301375f602092820183015296940135945050505056fea2646970667358221220352dd2347cc394aae405db3e3252ad980aa8346173d8f4b0953a542527ace78164736f6c634300081c0033";

  
      type SingletonFactoryConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: SingletonFactoryConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class SingletonFactory__factory extends ContractFactory {
    
      constructor(...args: SingletonFactoryConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<SingletonFactory & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): SingletonFactory__factory {
      return super.connect(runner) as SingletonFactory__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): SingletonFactoryInterface {
      return new Interface(_abi) as SingletonFactoryInterface;
    }
    
    override attach(address: string | Addressable): SingletonFactory {
      return super.attach(address) as SingletonFactory;
    }
  static connect(address: string, runner?: ContractRunner | null): SingletonFactory {
      return new Contract(address, _abi, runner) as unknown as SingletonFactory;
    }
  }

  
  