/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as simulateTxAccessorSol from './SimulateTxAccessor.sol/index.js';
export type { simulateTxAccessorSol };