// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface FallbackManager$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "FallbackManager";
  readonly sourceName: "contracts/base/FallbackManager.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"handler","type":"address"}],"name":"ChangedFallbackHandler","type":"event"},{"stateMutability":"nonpayable","type":"fallback"},{"inputs":[{"internalType":"address","name":"handler","type":"address"}],"name":"setFallbackHandler","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/base/FallbackManager.sol";
  readonly buildInfoId: "solc-0_8_28-438439afbf13652c0a40ba85fd75b4132274a7ae";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["FallbackManager"]: FallbackManager$Type;
    ["contracts/base/FallbackManager.sol:FallbackManager"]: FallbackManager$Type;
  }
}