/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc165HandlerSol from './ERC165Handler.sol/index.js';
export type { erc165HandlerSol };
import type * as extensibleBaseSol from './ExtensibleBase.sol/index.js';
export type { extensibleBaseSol };
import type * as fallbackHandlerSol from './FallbackHandler.sol/index.js';
export type { fallbackHandlerSol };
import type * as signatureVerifierMuxerSol from './SignatureVerifierMuxer.sol/index.js';
export type { signatureVerifierMuxerSol };
import type * as tokenCallbacksSol from './TokenCallbacks.sol/index.js';
export type { tokenCallbacksSol };