/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../common.js"
  import type { SimulateTxAccessor, SimulateTxAccessorInterface } from "../../../accessors/SimulateTxAccessor.sol/SimulateTxAccessor.js";

  const _abi = [
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "value",
        "type": "uint256"
      },
      {
        "internalType": "bytes",
        "name": "data",
        "type": "bytes"
      },
      {
        "internalType": "enum Enum.Operation",
        "name": "operation",
        "type": "uint8"
      }
    ],
    "name": "simulate",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "estimate",
        "type": "uint256"
      },
      {
        "internalType": "bool",
        "name": "success",
        "type": "bool"
      },
      {
        "internalType": "bytes",
        "name": "returnData",
        "type": "bytes"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x60a0604052348015600e575f5ffd5b503060805260805161032961002a5f395f606601526103295ff3fe608060405234801561000f575f5ffd5b5060043610610029575f3560e01c80631c5fb2111461002d575b5f5ffd5b61004061003b3660046101d0565b610058565b60405161004f93929190610275565b60405180910390f35b5f8060606001600160a01b037f00000000000000000000000000000000000000000000000000000000000000001630036100fe5760405162461bcd60e51b815260206004820152603960248201527f53696d756c61746554784163636573736f722073686f756c64206f6e6c79206260448201527f652063616c6c6564207669612064656c656761746563616c6c00000000000000606482015260840160405180910390fd5b5f5a9050610144898989898080601f0160208091040260200160405190810160405280939291908181526020018383808284375f920191909152508b925050505a610179565b92505a61015190826102ba565b935060405160203d0181016040523d81523d5f602083013e8092505050955095509592505050565b5f600183600181111561018e5761018e6102df565b036101a5575f5f8551602087018986f490506101b4565b5f5f855160208701888a87f190505b95945050505050565b8035600281106101cb575f5ffd5b919050565b5f5f5f5f5f608086880312156101e4575f5ffd5b85356001600160a01b03811681146101fa575f5ffd5b945060208601359350604086013567ffffffffffffffff81111561021c575f5ffd5b8601601f8101881361022c575f5ffd5b803567ffffffffffffffff811115610242575f5ffd5b886020828401011115610253575f5ffd5b60209190910193509150610269606087016101bd565b90509295509295909350565b8381528215156020820152606060408201525f82518060608401528060208501608085015e5f608082850101526080601f19601f830116840101915050949350505050565b818103818111156102d957634e487b7160e01b5f52601160045260245ffd5b92915050565b634e487b7160e01b5f52602160045260245ffdfea26469706673582212200920195cae3a49d6a15c4d5088bed0447764402a9890d2fb1274207e38f5f38064736f6c634300081c0033";

  
      type SimulateTxAccessorConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: SimulateTxAccessorConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class SimulateTxAccessor__factory extends ContractFactory {
    
      constructor(...args: SimulateTxAccessorConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<SimulateTxAccessor & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): SimulateTxAccessor__factory {
      return super.connect(runner) as SimulateTxAccessor__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): SimulateTxAccessorInterface {
      return new Interface(_abi) as SimulateTxAccessorInterface;
    }
    
    override attach(address: string | Addressable): SimulateTxAccessor {
      return super.attach(address) as SimulateTxAccessor;
    }
  static connect(address: string, runner?: ContractRunner | null): SimulateTxAccessor {
      return new Contract(address, _abi, runner) as unknown as SimulateTxAccessor;
    }
  }

  
  