/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IProxy__factory } from './IProxy__factory.js';
export { SafeProxy__factory } from './SafeProxy__factory.js';