/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, AddressLike, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../common.js"
  import type { SafeProxy, SafeProxyInterface } from "../../../proxies/SafeProxy.sol/SafeProxy.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_singleton",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "stateMutability": "payable",
    "type": "fallback"
  }
] as const;

  const _bytecode = "0x608060405234801561000f575f5ffd5b5060405161028938038061028983398181016040528101906100319190610142565b5f73ffffffffffffffffffffffffffffffffffffffff168173ffffffffffffffffffffffffffffffffffffffff160361009f576040517f08c379a0000000000000000000000000000000000000000000000000000000008152600401610096906101ed565b60405180910390fd5b805f5f6101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055505061020b565b5f5ffd5b5f73ffffffffffffffffffffffffffffffffffffffff82169050919050565b5f610111826100e8565b9050919050565b61012181610107565b811461012b575f5ffd5b50565b5f8151905061013c81610118565b92915050565b5f60208284031215610157576101566100e4565b5b5f6101648482850161012e565b91505092915050565b5f82825260208201905092915050565b7f496e76616c69642073696e676c65746f6e20616464726573732070726f7669645f8201527f6564000000000000000000000000000000000000000000000000000000000000602082015250565b5f6101d760228361016d565b91506101e28261017d565b604082019050919050565b5f6020820190508181035f830152610204816101cb565b9050919050565b6072806102175f395ff3fe60806040525f5463a619486e5f3560e01c036021578060601b606c5260206060f35b365f5f375f5f365f845af43d5f5f3e806038573d5ffd5b3d5ff3fea2646970667358221220bd2a584447cede9ef6f3418982259b7a8301da6b409b639a855baee51186670a64736f6c634300081c0033";

  
      type SafeProxyConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: SafeProxyConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class SafeProxy__factory extends ContractFactory {
    
      constructor(...args: SafeProxyConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(_singleton: AddressLike, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(_singleton, overrides || {});
    };
    override deploy(_singleton: AddressLike, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(_singleton, overrides || {}) as Promise<SafeProxy & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): SafeProxy__factory {
      return super.connect(runner) as SafeProxy__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): SafeProxyInterface {
      return new Interface(_abi) as SafeProxyInterface;
    }
    
    override attach(address: string | Addressable): SafeProxy {
      return super.attach(address) as SafeProxy;
    }
  static connect(address: string, runner?: ContractRunner | null): SafeProxy {
      return new Contract(address, _abi, runner) as unknown as SafeProxy;
    }
  }

  
  