/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, AddressLike, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../common.js"
  import type { SafeProxy, SafeProxyInterface } from "../../../proxies/SafeProxy.sol/SafeProxy.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_singleton",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "stateMutability": "payable",
    "type": "fallback"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b5060405161015e38038061015e833981016040819052602b9160b2565b6001600160a01b038116608f5760405162461bcd60e51b815260206004820152602260248201527f496e76616c69642073696e676c65746f6e20616464726573732070726f766964604482015261195960f21b606482015260840160405180910390fd5b5f80546001600160a01b0319166001600160a01b039290921691909117905560dd565b5f6020828403121560c1575f5ffd5b81516001600160a01b038116811460d6575f5ffd5b9392505050565b6075806100e95f395ff3fe60806040525f5463a619486e5f3560e01c036021578060601b606c5260206060f35b365f5f375f5f365f845af490503d5f5f3e80603a573d5ffd5b503d5ff3fea2646970667358221220f3600788d7860fc7ef35306e0c414dc298547c04274201f558481af98947bc9f64736f6c634300081c0033";

  
      type SafeProxyConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: SafeProxyConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class SafeProxy__factory extends ContractFactory {
    
      constructor(...args: SafeProxyConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(_singleton: AddressLike, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(_singleton, overrides || {});
    };
    override deploy(_singleton: AddressLike, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(_singleton, overrides || {}) as Promise<SafeProxy & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): SafeProxy__factory {
      return super.connect(runner) as SafeProxy__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): SafeProxyInterface {
      return new Interface(_abi) as SafeProxyInterface;
    }
    
    override attach(address: string | Addressable): SafeProxy {
      return super.attach(address) as SafeProxy;
    }
  static connect(address: string, runner?: ContractRunner | null): SafeProxy {
      return new Contract(address, _abi, runner) as unknown as SafeProxy;
    }
  }

  
  