/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { INativeCurrencyPaymentFallback, INativeCurrencyPaymentFallbackInterface } from "../../../interfaces/INativeCurrencyPaymentFallback.sol/INativeCurrencyPaymentFallback.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "sender",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "value",
        "type": "uint256"
      }
    ],
    "name": "SafeReceived",
    "type": "event"
  },
  {
    "stateMutability": "payable",
    "type": "receive"
  }
] as const;

  export class INativeCurrencyPaymentFallback__factory {
    static readonly abi = _abi;
    static createInterface(): INativeCurrencyPaymentFallbackInterface {
      return new Interface(_abi) as INativeCurrencyPaymentFallbackInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): INativeCurrencyPaymentFallback {
      return new Contract(address, _abi, runner) as unknown as INativeCurrencyPaymentFallback;
    }
  }
  