/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ExtensibleBase } from './ExtensibleBase.js';
export type { IFallbackMethod } from './IFallbackMethod.js';
export type { IStaticFallbackMethod } from './IStaticFallbackMethod.js';