/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as compatibilityFallbackHandlerSol from './CompatibilityFallbackHandler.sol/index.js';
export type { compatibilityFallbackHandlerSol };
import type * as extensibleFallbackHandlerSol from './ExtensibleFallbackHandler.sol/index.js';
export type { extensibleFallbackHandlerSol };
import type * as tokenCallbackHandlerSol from './TokenCallbackHandler.sol/index.js';
export type { tokenCallbackHandlerSol };
import type * as extensible from './extensible/index.js';
export type { extensible };