/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ERC1271, ERC1271Interface } from "../../../../handler/extensible/SignatureVerifierMuxer.sol/ERC1271.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "hash",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "signature",
        "type": "bytes"
      }
    ],
    "name": "isValidSignature",
    "outputs": [
      {
        "internalType": "bytes4",
        "name": "magicValue",
        "type": "bytes4"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class ERC1271__factory {
    static readonly abi = _abi;
    static createInterface(): ERC1271Interface {
      return new Interface(_abi) as ERC1271Interface;
    }
    static connect(address: string, runner?: ContractRunner | null): ERC1271 {
      return new Contract(address, _abi, runner) as unknown as ERC1271;
    }
  }
  