/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ISafeSignatureVerifier, ISafeSignatureVerifierInterface } from "../../../../handler/extensible/SignatureVerifierMuxer.sol/ISafeSignatureVerifier.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "contract ISafe",
        "name": "safe",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "sender",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "_hash",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "domainSeparator",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "typeHash",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "encodeData",
        "type": "bytes"
      },
      {
        "internalType": "bytes",
        "name": "payload",
        "type": "bytes"
      }
    ],
    "name": "isValidSafeSignature",
    "outputs": [
      {
        "internalType": "bytes4",
        "name": "magic",
        "type": "bytes4"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class ISafeSignatureVerifier__factory {
    static readonly abi = _abi;
    static createInterface(): ISafeSignatureVerifierInterface {
      return new Interface(_abi) as ISafeSignatureVerifierInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ISafeSignatureVerifier {
      return new Contract(address, _abi, runner) as unknown as ISafeSignatureVerifier;
    }
  }
  