/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ISignatureVerifierMuxer, ISignatureVerifierMuxerInterface } from "../../../../handler/extensible/SignatureVerifierMuxer.sol/ISignatureVerifierMuxer.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "contract ISafe",
        "name": "safe",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "domainSeparator",
        "type": "bytes32"
      }
    ],
    "name": "domainVerifiers",
    "outputs": [
      {
        "internalType": "contract ISafeSignatureVerifier",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "domainSeparator",
        "type": "bytes32"
      },
      {
        "internalType": "contract ISafeSignatureVerifier",
        "name": "verifier",
        "type": "address"
      }
    ],
    "name": "setDomainVerifier",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class ISignatureVerifierMuxer__factory {
    static readonly abi = _abi;
    static createInterface(): ISignatureVerifierMuxerInterface {
      return new Interface(_abi) as ISignatureVerifierMuxerInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ISignatureVerifierMuxer {
      return new Contract(address, _abi, runner) as unknown as ISignatureVerifierMuxer;
    }
  }
  