/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { SignatureVerifierMuxer, SignatureVerifierMuxerInterface } from "../../../../handler/extensible/SignatureVerifierMuxer.sol/SignatureVerifierMuxer.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "contract ISafe",
        "name": "safe",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "domainSeparator",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "contract ISafeSignatureVerifier",
        "name": "oldVerifier",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "contract ISafeSignatureVerifier",
        "name": "newVerifier",
        "type": "address"
      }
    ],
    "name": "ChangedDomainVerifier",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "contract ISafe",
        "name": "safe",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "bytes4",
        "name": "selector",
        "type": "bytes4"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "oldMethod",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "newMethod",
        "type": "bytes32"
      }
    ],
    "name": "ChangedSafeMethod",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "contract ISafe",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "name": "domainVerifiers",
    "outputs": [
      {
        "internalType": "contract ISafeSignatureVerifier",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "_hash",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "signature",
        "type": "bytes"
      }
    ],
    "name": "isValidSignature",
    "outputs": [
      {
        "internalType": "bytes4",
        "name": "magic",
        "type": "bytes4"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "contract ISafe",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "bytes4",
        "name": "",
        "type": "bytes4"
      }
    ],
    "name": "safeMethods",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "domainSeparator",
        "type": "bytes32"
      },
      {
        "internalType": "contract ISafeSignatureVerifier",
        "name": "newVerifier",
        "type": "address"
      }
    ],
    "name": "setDomainVerifier",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class SignatureVerifierMuxer__factory {
    static readonly abi = _abi;
    static createInterface(): SignatureVerifierMuxerInterface {
      return new Interface(_abi) as SignatureVerifierMuxerInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): SignatureVerifierMuxer {
      return new Contract(address, _abi, runner) as unknown as SignatureVerifierMuxer;
    }
  }
  