/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface SimpleGuardInterface extends Interface {
    getFunction(nameOrSignature: "checkAfterExecution" | "checkTransaction" | "setGuard" | "supportsInterface"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ChangedGuard" | "ExecutionSuccess"): EventFragment;

    encodeFunctionData(functionFragment: 'checkAfterExecution', values: [BytesLike, boolean]): string;
encodeFunctionData(functionFragment: 'checkTransaction', values: [AddressLike, BigNumberish, BytesLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish, AddressLike, AddressLike, BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setGuard', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'checkAfterExecution', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'checkTransaction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setGuard', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
  }

  
    export namespace ChangedGuardEvent {
      export type InputTuple = [guard: AddressLike];
      export type OutputTuple = [guard: string];
      export interface OutputObject {guard: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ExecutionSuccessEvent {
      export type InputTuple = [hash: BytesLike];
      export type OutputTuple = [hash: string];
      export interface OutputObject {hash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SimpleGuard extends BaseContract {
    
    connect(runner?: ContractRunner | null): SimpleGuard;
    waitForDeployment(): Promise<this>;

    interface: SimpleGuardInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    checkAfterExecution: TypedContractMethod<
      [hash: BytesLike, success: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    checkTransaction: TypedContractMethod<
      [to: AddressLike, value: BigNumberish, data: BytesLike, operation: BigNumberish, safeTxGas: BigNumberish, baseGas: BigNumberish, gasPrice: BigNumberish, gasToken: AddressLike, refundReceiver: AddressLike, signatures: BytesLike, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setGuard: TypedContractMethod<
      [guard: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'checkAfterExecution'): TypedContractMethod<
      [hash: BytesLike, success: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'checkTransaction'): TypedContractMethod<
      [to: AddressLike, value: BigNumberish, data: BytesLike, operation: BigNumberish, safeTxGas: BigNumberish, baseGas: BigNumberish, gasPrice: BigNumberish, gasToken: AddressLike, refundReceiver: AddressLike, signatures: BytesLike, msgSender: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setGuard'): TypedContractMethod<
      [guard: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'ChangedGuard'): TypedContractEvent<ChangedGuardEvent.InputTuple, ChangedGuardEvent.OutputTuple, ChangedGuardEvent.OutputObject>;
getEvent(key: 'ExecutionSuccess'): TypedContractEvent<ExecutionSuccessEvent.InputTuple, ExecutionSuccessEvent.OutputTuple, ExecutionSuccessEvent.OutputObject>;

    filters: {
      
      'ChangedGuard(address)': TypedContractEvent<ChangedGuardEvent.InputTuple, ChangedGuardEvent.OutputTuple, ChangedGuardEvent.OutputObject>;
      ChangedGuard: TypedContractEvent<ChangedGuardEvent.InputTuple, ChangedGuardEvent.OutputTuple, ChangedGuardEvent.OutputObject>;
    

      'ExecutionSuccess(bytes32)': TypedContractEvent<ExecutionSuccessEvent.InputTuple, ExecutionSuccessEvent.OutputTuple, ExecutionSuccessEvent.OutputObject>;
      ExecutionSuccess: TypedContractEvent<ExecutionSuccessEvent.InputTuple, ExecutionSuccessEvent.OutputTuple, ExecutionSuccessEvent.OutputObject>;
    
    };
  }