// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface SecuredTokenTransfer$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "SecuredTokenTransfer";
  readonly sourceName: "contracts/common/SecuredTokenTransfer.sol";
  readonly abi: [];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/common/SecuredTokenTransfer.sol";
  readonly buildInfoId: "solc-0_8_28-91df60bfe7423093716df687715f88debc9f9838";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["SecuredTokenTransfer"]: SecuredTokenTransfer$Type;
    ["contracts/common/SecuredTokenTransfer.sol:SecuredTokenTransfer"]: SecuredTokenTransfer$Type;
  }
}