// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface SignatureDecoder$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "SignatureDecoder";
  readonly sourceName: "contracts/common/SignatureDecoder.sol";
  readonly abi: [];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/common/SignatureDecoder.sol";
  readonly buildInfoId: "solc-0_8_28-8f51bcdd57cd1228bd977e279b81c5b1c970ddd9";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["SignatureDecoder"]: SignatureDecoder$Type;
    ["contracts/common/SignatureDecoder.sol:SignatureDecoder"]: SignatureDecoder$Type;
  }
}