// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ErrorMessage$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ErrorMessage";
  readonly sourceName: "contracts/libraries/ErrorMessage.sol";
  readonly abi: [];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/ErrorMessage.sol";
  readonly buildInfoId: "solc-0_8_28-ed2d128c3ac1e98a551cdd21051ecbf6dd081352";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ErrorMessage"]: ErrorMessage$Type;
    ["contracts/libraries/ErrorMessage.sol:ErrorMessage"]: ErrorMessage$Type;
  }
}