/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../common.js"
  import type { MultiSendCallOnly, MultiSendCallOnlyInterface } from "../../../libraries/MultiSendCallOnly.sol/MultiSendCallOnly.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "transactions",
        "type": "bytes"
      }
    ],
    "name": "multiSend",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b506102938061001c5f395ff3fe60806040526004361061001d575f3560e01c80638d80ff0a14610021575b5f5ffd5b61003b60048036038101906100369190610216565b61003d565b005b805160205b818110156100c4578083015160f81c6001820184015160601c308115028117905060158301850151603584018601516055850187015f855f811461008d576001811461009c576100a0565b5f5f8585888a5af191506100a0565b5f5ffd5b50806100b1576040513d5f823e3d81fd5b8260550187019650505050505050610042565b505050565b5f604051905090565b5f5ffd5b5f5ffd5b5f5ffd5b5f5ffd5b5f601f19601f8301169050919050565b7f4e487b71000000000000000000000000000000000000000000000000000000005f52604160045260245ffd5b610128826100e2565b810181811067ffffffffffffffff82111715610147576101466100f2565b5b80604052505050565b5f6101596100c9565b9050610165828261011f565b919050565b5f67ffffffffffffffff821115610184576101836100f2565b5b61018d826100e2565b9050602081019050919050565b828183375f83830152505050565b5f6101ba6101b58461016a565b610150565b9050828152602081018484840111156101d6576101d56100de565b5b6101e184828561019a565b509392505050565b5f82601f8301126101fd576101fc6100da565b5b813561020d8482602086016101a8565b91505092915050565b5f6020828403121561022b5761022a6100d2565b5b5f82013567ffffffffffffffff811115610248576102476100d6565b5b610254848285016101e9565b9150509291505056fea2646970667358221220cd6a4c2fd4d892e75e81c8f7dd3497d6c41678df6db4c45765afc319d12d734164736f6c634300081c0033";

  
      type MultiSendCallOnlyConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MultiSendCallOnlyConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MultiSendCallOnly__factory extends ContractFactory {
    
      constructor(...args: MultiSendCallOnlyConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MultiSendCallOnly & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MultiSendCallOnly__factory {
      return super.connect(runner) as MultiSendCallOnly__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MultiSendCallOnlyInterface {
      return new Interface(_abi) as MultiSendCallOnlyInterface;
    }
    
    override attach(address: string | Addressable): MultiSendCallOnly {
      return super.attach(address) as MultiSendCallOnly;
    }
  static connect(address: string, runner?: ContractRunner | null): MultiSendCallOnly {
      return new Contract(address, _abi, runner) as unknown as MultiSendCallOnly;
    }
  }

  
  