/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../common.js"
  import type { MultiSendCallOnly, MultiSendCallOnlyInterface } from "../../../libraries/MultiSendCallOnly.sol/MultiSendCallOnly.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "transactions",
        "type": "bytes"
      }
    ],
    "name": "multiSend",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b506101b78061001c5f395ff3fe60806040526004361061001d575f3560e01c80638d80ff0a14610021575b5f5ffd5b61003461002f3660046100ce565b610036565b005b805160205b818110156100b557828101805160018201516015830151603584015160f89390931c9360609290921c80153002179290916055015f858015610084576001811461001d5761008f565b5f5f8585888a5af191505b50806100a25760405195503d5f873e3d86fd5b505080605501850194505050505061003b565b505050565b634e487b7160e01b5f52604160045260245ffd5b5f602082840312156100de575f5ffd5b813567ffffffffffffffff8111156100f4575f5ffd5b8201601f81018413610104575f5ffd5b803567ffffffffffffffff81111561011e5761011e6100ba565b604051601f8201601f19908116603f0116810167ffffffffffffffff8111828210171561014d5761014d6100ba565b604052818152828201602001861015610164575f5ffd5b816020840160208301375f9181016020019190915294935050505056fea2646970667358221220ac4563c1c24cd7b20efc4d2f12d8ee67f37afe48c1b52378bfd13a72a6da669064736f6c634300081c0033";

  
      type MultiSendCallOnlyConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MultiSendCallOnlyConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MultiSendCallOnly__factory extends ContractFactory {
    
      constructor(...args: MultiSendCallOnlyConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MultiSendCallOnly & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MultiSendCallOnly__factory {
      return super.connect(runner) as MultiSendCallOnly__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MultiSendCallOnlyInterface {
      return new Interface(_abi) as MultiSendCallOnlyInterface;
    }
    
    override attach(address: string | Addressable): MultiSendCallOnly {
      return super.attach(address) as MultiSendCallOnly;
    }
  static connect(address: string, runner?: ContractRunner | null): MultiSendCallOnly {
      return new Contract(address, _abi, runner) as unknown as MultiSendCallOnly;
    }
  }

  
  