// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface EIP712$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "EIP712";
  readonly sourceName: "contracts/handler/extensible/SignatureVerifierMuxer.sol";
  readonly abi: [];
  readonly bytecode: "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220fefecdee7ced55b045fa35f1c999d13772f5a7e709901cbba876581bfc1e0e1864736f6c634300081c0033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220fefecdee7ced55b045fa35f1c999d13772f5a7e709901cbba876581bfc1e0e1864736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/handler/extensible/SignatureVerifierMuxer.sol";
  readonly buildInfoId: "solc-0_8_28-ed2d128c3ac1e98a551cdd21051ecbf6dd081352";
};

export interface ERC1271$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ERC1271";
  readonly sourceName: "contracts/handler/extensible/SignatureVerifierMuxer.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes32","name":"hash","type":"bytes32"},{"internalType":"bytes","name":"signature","type":"bytes"}],"name":"isValidSignature","outputs":[{"internalType":"bytes4","name":"magicValue","type":"bytes4"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/handler/extensible/SignatureVerifierMuxer.sol";
  readonly buildInfoId: "solc-0_8_28-ed2d128c3ac1e98a551cdd21051ecbf6dd081352";
};

export interface ISafeSignatureVerifier$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ISafeSignatureVerifier";
  readonly sourceName: "contracts/handler/extensible/SignatureVerifierMuxer.sol";
  readonly abi: [{"inputs":[{"internalType":"contract ISafe","name":"safe","type":"address"},{"internalType":"address","name":"sender","type":"address"},{"internalType":"bytes32","name":"_hash","type":"bytes32"},{"internalType":"bytes32","name":"domainSeparator","type":"bytes32"},{"internalType":"bytes32","name":"typeHash","type":"bytes32"},{"internalType":"bytes","name":"encodeData","type":"bytes"},{"internalType":"bytes","name":"payload","type":"bytes"}],"name":"isValidSafeSignature","outputs":[{"internalType":"bytes4","name":"magic","type":"bytes4"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/handler/extensible/SignatureVerifierMuxer.sol";
  readonly buildInfoId: "solc-0_8_28-ed2d128c3ac1e98a551cdd21051ecbf6dd081352";
};

export interface ISignatureVerifierMuxer$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ISignatureVerifierMuxer";
  readonly sourceName: "contracts/handler/extensible/SignatureVerifierMuxer.sol";
  readonly abi: [{"inputs":[{"internalType":"contract ISafe","name":"safe","type":"address"},{"internalType":"bytes32","name":"domainSeparator","type":"bytes32"}],"name":"domainVerifiers","outputs":[{"internalType":"contract ISafeSignatureVerifier","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes32","name":"domainSeparator","type":"bytes32"},{"internalType":"contract ISafeSignatureVerifier","name":"verifier","type":"address"}],"name":"setDomainVerifier","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/handler/extensible/SignatureVerifierMuxer.sol";
  readonly buildInfoId: "solc-0_8_28-ed2d128c3ac1e98a551cdd21051ecbf6dd081352";
};

export interface SignatureVerifierMuxer$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "SignatureVerifierMuxer";
  readonly sourceName: "contracts/handler/extensible/SignatureVerifierMuxer.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":true,"internalType":"contract ISafe","name":"safe","type":"address"},{"indexed":false,"internalType":"bytes32","name":"domainSeparator","type":"bytes32"},{"indexed":false,"internalType":"contract ISafeSignatureVerifier","name":"oldVerifier","type":"address"},{"indexed":false,"internalType":"contract ISafeSignatureVerifier","name":"newVerifier","type":"address"}],"name":"ChangedDomainVerifier","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"contract ISafe","name":"safe","type":"address"},{"indexed":false,"internalType":"bytes4","name":"selector","type":"bytes4"},{"indexed":false,"internalType":"bytes32","name":"oldMethod","type":"bytes32"},{"indexed":false,"internalType":"bytes32","name":"newMethod","type":"bytes32"}],"name":"ChangedSafeMethod","type":"event"},{"inputs":[{"internalType":"contract ISafe","name":"","type":"address"},{"internalType":"bytes32","name":"","type":"bytes32"}],"name":"domainVerifiers","outputs":[{"internalType":"contract ISafeSignatureVerifier","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes32","name":"_hash","type":"bytes32"},{"internalType":"bytes","name":"signature","type":"bytes"}],"name":"isValidSignature","outputs":[{"internalType":"bytes4","name":"magic","type":"bytes4"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"contract ISafe","name":"","type":"address"},{"internalType":"bytes4","name":"","type":"bytes4"}],"name":"safeMethods","outputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes32","name":"domainSeparator","type":"bytes32"},{"internalType":"contract ISafeSignatureVerifier","name":"newVerifier","type":"address"}],"name":"setDomainVerifier","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/handler/extensible/SignatureVerifierMuxer.sol";
  readonly buildInfoId: "solc-0_8_28-ed2d128c3ac1e98a551cdd21051ecbf6dd081352";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["EIP712"]: EIP712$Type
    ["ERC1271"]: ERC1271$Type
    ["ISafeSignatureVerifier"]: ISafeSignatureVerifier$Type
    ["ISignatureVerifierMuxer"]: ISignatureVerifierMuxer$Type
    ["SignatureVerifierMuxer"]: SignatureVerifierMuxer$Type;
    ["contracts/handler/extensible/SignatureVerifierMuxer.sol:EIP712"]: EIP712$Type
    ["contracts/handler/extensible/SignatureVerifierMuxer.sol:ERC1271"]: ERC1271$Type
    ["contracts/handler/extensible/SignatureVerifierMuxer.sol:ISafeSignatureVerifier"]: ISafeSignatureVerifier$Type
    ["contracts/handler/extensible/SignatureVerifierMuxer.sol:ISignatureVerifierMuxer"]: ISignatureVerifierMuxer$Type
    ["contracts/handler/extensible/SignatureVerifierMuxer.sol:SignatureVerifierMuxer"]: SignatureVerifierMuxer$Type;
  }
}