// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface HandlerContext$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "HandlerContext";
  readonly sourceName: "contracts/handler/HandlerContext.sol";
  readonly abi: [];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/handler/HandlerContext.sol";
  readonly buildInfoId: "solc-0_8_28-90e4de88ba6b0d49ea7994b5f15a6a457c9b4da1";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["HandlerContext"]: HandlerContext$Type;
    ["contracts/handler/HandlerContext.sol:HandlerContext"]: HandlerContext$Type;
  }
}