/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nativeCurrencyPaymentFallbackSol from './NativeCurrencyPaymentFallback.sol/index.js';
export type { nativeCurrencyPaymentFallbackSol };
import type * as storageAccessibleSol from './StorageAccessible.sol/index.js';
export type { storageAccessibleSol };