// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IStorageAccessible$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IStorageAccessible";
  readonly sourceName: "contracts/interfaces/IStorageAccessible.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"offset","type":"uint256"},{"internalType":"uint256","name":"length","type":"uint256"}],"name":"getStorageAt","outputs":[{"internalType":"bytes","name":"","type":"bytes"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"targetContract","type":"address"},{"internalType":"bytes","name":"calldataPayload","type":"bytes"}],"name":"simulateAndRevert","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IStorageAccessible.sol";
  readonly buildInfoId: "solc-0_8_28-4dad861290f3ed5f708c889529bff77abcfb63cd";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IStorageAccessible"]: IStorageAccessible$Type;
    ["contracts/interfaces/IStorageAccessible.sol:IStorageAccessible"]: IStorageAccessible$Type;
  }
}