/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface SingletonFactoryInterface extends Interface {
    getFunction(nameOrSignature: "createdContracts" | "deploy"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'createdContracts', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'deploy', values: [BytesLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'createdContracts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deploy', data: BytesLike): Result;
  }

  

  export interface SingletonFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): SingletonFactory;
    waitForDeployment(): Promise<this>;

    interface: SingletonFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createdContracts: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    deploy: TypedContractMethod<
      [_initCode: BytesLike, _salt: BytesLike, ],
      [string],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createdContracts'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'deploy'): TypedContractMethod<
      [_initCode: BytesLike, _salt: BytesLike, ],
      [string],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }