// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface MarshalLib$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MarshalLib";
  readonly sourceName: "contracts/handler/extensible/MarshalLib.sol";
  readonly abi: [];
  readonly bytecode: "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea264697066735822122075b778247920abe2c3f43579d932ef683d9c26c9103367d57e90db5a9eec317364736f6c634300081c0033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f5ffdfea264697066735822122075b778247920abe2c3f43579d932ef683d9c26c9103367d57e90db5a9eec317364736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/handler/extensible/MarshalLib.sol";
  readonly buildInfoId: "solc-0_8_28-ed2d128c3ac1e98a551cdd21051ecbf6dd081352";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["MarshalLib"]: MarshalLib$Type;
    ["contracts/handler/extensible/MarshalLib.sol:MarshalLib"]: MarshalLib$Type;
  }
}