// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface MarshalLib$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MarshalLib";
  readonly sourceName: "contracts/handler/extensible/MarshalLib.sol";
  readonly abi: [];
  readonly bytecode: "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea264697066735822122037d7fd78d95b1df20aa1f70f345badb7e47f0ba7847961243e420f567de4c93664736f6c634300081c0033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f5ffdfea264697066735822122037d7fd78d95b1df20aa1f70f345badb7e47f0ba7847961243e420f567de4c93664736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/handler/extensible/MarshalLib.sol";
  readonly buildInfoId: "solc-0_8_28-14d948f4656bfff77d01d616afb1937fb4d46f13";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["MarshalLib"]: MarshalLib$Type;
    ["contracts/handler/extensible/MarshalLib.sol:MarshalLib"]: MarshalLib$Type;
  }
}