/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ExtensibleBase, ExtensibleBaseInterface } from "../../../../handler/extensible/ExtensibleBase.sol/ExtensibleBase.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "contract ISafe",
        "name": "safe",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "bytes4",
        "name": "selector",
        "type": "bytes4"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "oldMethod",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "newMethod",
        "type": "bytes32"
      }
    ],
    "name": "ChangedSafeMethod",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "contract ISafe",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "bytes4",
        "name": "",
        "type": "bytes4"
      }
    ],
    "name": "safeMethods",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class ExtensibleBase__factory {
    static readonly abi = _abi;
    static createInterface(): ExtensibleBaseInterface {
      return new Interface(_abi) as ExtensibleBaseInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ExtensibleBase {
      return new Contract(address, _abi, runner) as unknown as ExtensibleBase;
    }
  }
  