/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IFallbackMethod, IFallbackMethodInterface } from "../../../../handler/extensible/ExtensibleBase.sol/IFallbackMethod.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "contract ISafe",
        "name": "safe",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "sender",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "value",
        "type": "uint256"
      },
      {
        "internalType": "bytes",
        "name": "data",
        "type": "bytes"
      }
    ],
    "name": "handle",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "result",
        "type": "bytes"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IFallbackMethod__factory {
    static readonly abi = _abi;
    static createInterface(): IFallbackMethodInterface {
      return new Interface(_abi) as IFallbackMethodInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IFallbackMethod {
      return new Contract(address, _abi, runner) as unknown as IFallbackMethod;
    }
  }
  