/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ExtensibleBase__factory } from './ExtensibleBase__factory.js';
export { IFallbackMethod__factory } from './IFallbackMethod__factory.js';
export { IStaticFallbackMethod__factory } from './IStaticFallbackMethod__factory.js';