// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ISignatureValidator$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ISignatureValidator";
  readonly sourceName: "contracts/interfaces/ISignatureValidator.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes32","name":"_hash","type":"bytes32"},{"internalType":"bytes","name":"_signature","type":"bytes"}],"name":"isValidSignature","outputs":[{"internalType":"bytes4","name":"","type":"bytes4"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/ISignatureValidator.sol";
  readonly buildInfoId: "solc-0_8_28-ed2d128c3ac1e98a551cdd21051ecbf6dd081352";
};

export interface ISignatureValidatorConstants$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ISignatureValidatorConstants";
  readonly sourceName: "contracts/interfaces/ISignatureValidator.sol";
  readonly abi: [];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/ISignatureValidator.sol";
  readonly buildInfoId: "solc-0_8_28-ed2d128c3ac1e98a551cdd21051ecbf6dd081352";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ISignatureValidator"]: ISignatureValidator$Type
    ["ISignatureValidatorConstants"]: ISignatureValidatorConstants$Type;
    ["contracts/interfaces/ISignatureValidator.sol:ISignatureValidator"]: ISignatureValidator$Type
    ["contracts/interfaces/ISignatureValidator.sol:ISignatureValidatorConstants"]: ISignatureValidatorConstants$Type;
  }
}