/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FallbackHandler } from './FallbackHandler.js';
export type { IFallbackHandler } from './IFallbackHandler.js';