/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../common.js"
  import type { SafeToL2Setup, SafeToL2SetupInterface } from "../../../libraries/SafeToL2Setup.sol/SafeToL2Setup.js";

  const _abi = [
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "address",
        "name": "singleton",
        "type": "address"
      }
    ],
    "name": "ChangedMasterCopy",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "l2Singleton",
        "type": "address"
      }
    ],
    "name": "setupToL2",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x60a0604052348015600e575f5ffd5b503060805260805161024861002a5f395f604c01526102485ff3fe608060405234801561000f575f5ffd5b5060043610610029575f3560e01c8063fe51f6431461002d575b5f5ffd5b61004061003b3660046101e5565b610042565b005b6001600160a01b037f00000000000000000000000000000000000000000000000000000000000000001630036100dc5760405162461bcd60e51b815260206004820152603460248201527f53616665546f4c3253657475702073686f756c64206f6e6c792062652063616c6044820152731b1959081d9a584819195b1959d85d1958d85b1b60621b60648201526084015b60405180910390fd5b600554156101375760405162461bcd60e51b815260206004820152602260248201527f53616665206d7573742068617665206e6f7420657865637574656420616e79206044820152610e8f60f31b60648201526084016100d3565b80803b5f036101885760405162461bcd60e51b815260206004820152601c60248201527f4163636f756e7420646f65736e277420636f6e7461696e20636f64650000000060448201526064016100d3565b466001146101e1575f80546001600160a01b0319166001600160a01b0384169081179091556040519081527f75e41bc35ff1bf14d81d1d2f649c0084a0f974f9289c803ec9898eeec4c8d0b89060200160405180910390a15b5050565b5f602082840312156101f5575f5ffd5b81356001600160a01b038116811461020b575f5ffd5b939250505056fea26469706673582212207605f7f3306438168d04a348394ac3a5782d6cbe211ed12f8a74e710bca0caa364736f6c634300081c0033";

  
      type SafeToL2SetupConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: SafeToL2SetupConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class SafeToL2Setup__factory extends ContractFactory {
    
      constructor(...args: SafeToL2SetupConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<SafeToL2Setup & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): SafeToL2Setup__factory {
      return super.connect(runner) as SafeToL2Setup__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): SafeToL2SetupInterface {
      return new Interface(_abi) as SafeToL2SetupInterface;
    }
    
    override attach(address: string | Addressable): SafeToL2Setup {
      return super.attach(address) as SafeToL2Setup;
    }
  static connect(address: string, runner?: ContractRunner | null): SafeToL2Setup {
      return new Contract(address, _abi, runner) as unknown as SafeToL2Setup;
    }
  }

  
  