// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface SafeStorage$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "SafeStorage";
  readonly sourceName: "contracts/libraries/SafeStorage.sol";
  readonly abi: [];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/SafeStorage.sol";
  readonly buildInfoId: "solc-0_8_28-59031884193fcb1eec27b09d232bd38894c7f9fd";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["SafeStorage"]: SafeStorage$Type;
    ["contracts/libraries/SafeStorage.sol:SafeStorage"]: SafeStorage$Type;
  }
}